title: Living Culture Journal
description: A collaborative digital journal exploring cultural themes
theme: jekyll-theme-cayman
show_downloads: false
github:
  repository_url: https://github.com/ruqdr/living-culture-journal
